In [1]:
from fastai.text import *
from data_helpers.Data import *

In [2]:
sent_num_file = ["aspect_0.count", "test_aspect_0.count"]
rating_file = ["aspect_0.rating", "test_aspect_0.rating"]
content_file = ["aspect_0.txt", "test_aspect_0.txt"]

dataset_dir = "./data/hotel_balance_LengthFix1_3000per/"

In [3]:
def concat_to_doc(sent_list, sent_count):
    start_index = 0
    docs = []
    for s in sent_count:
        doc = " . ".join(sent_list[start_index:start_index + s])
        docs.append(doc)
        start_index = start_index + s
    return docs

In [4]:
TRAIN_DATA = 0
TEST_DATA = 1

### load train

In [5]:
sent_count_train = list(open(dataset_dir + sent_num_file[TRAIN_DATA], "r").readlines())
sent_count_train = [int(s) for s in sent_count_train if (len(s) > 0 and s != "\n")]
sent_count_train[0:5]

[10, 14, 14, 24, 23]

In [6]:
aspect_rating_train = list(open(dataset_dir + rating_file[TRAIN_DATA], "r").readlines())
aspect_rating_train = [s for s in aspect_rating_train if (len(s) > 0 and s != "\n")]
aspect_rating_train[0:5]

['5 5 5 5 5 5 \n',
 '5 4 5 5 5 5 \n',
 '2 1 2 2 3 2 \n',
 '4 3 4 3 5 4 \n',
 '4 3 2 3 3 5 \n']

In [7]:
aspect_rating_train = [s.split(" ") for s in aspect_rating_train]
aspect_rating_train = np.array(aspect_rating_train)[:, 0:-1]
aspect_rating_train = aspect_rating_train.astype(np.int) - 1
aspect_rating_train[0:5]

array([[4, 4, 4, 4, 4, 4],
       [4, 3, 4, 4, 4, 4],
       [1, 0, 1, 1, 2, 1],
       [3, 2, 3, 2, 4, 3],
       [3, 2, 1, 2, 2, 4]])

In [9]:
sents_train = list(open(dataset_dir + content_file[TRAIN_DATA], "r").readlines())
sents_train = [s.strip() for s in sents_train]
len(sents_train)

265556

In [10]:
sents_train[0:5]

['we had the most wonderful time at the excellence',
 'we opted for the excellence club and it was well worht it for the perks',
 'roberto puello who was the club manager did an extra special job of making us feel welcomed',
 'we took some great pictures that looked like postcards',
 'the food was excellent the pizza was close to being our favorite']

In [11]:
docs_train = concat_to_doc(sents_train, sent_count_train)
docs_train[0]

"we had the most wonderful time at the excellence . we opted for the excellence club and it was well worht it for the perks . roberto puello who was the club manager did an extra special job of making us feel welcomed . we took some great pictures that looked like postcards . the food was excellent the pizza was close to being our favorite . the shows were great especially the michael jackson and the 70's  80's night . the french resturant was probably our favorite . we will definately be back for an anniversary trip . we made some friends but had plenty of privcacy as well . the rooms were great and everytime we left and came back it was cleaned , towels restocked and the bar was as well"

In [13]:
df_train = pd.DataFrame(docs_train)
df_train.head()

0
0  we had the most wonderful time at the excellen...
1  a truly fantastic place xmas  we have just ret...
2  too sick to enjoy the ride to and form the air...
3  relaxing and fun , but . i rang in the new yea...
4  somewhat excellence we just returned from a on...

### load test

In [14]:
sent_count_test = list(open(dataset_dir + sent_num_file[TEST_DATA], "r").readlines())
sent_count_test = [int(s) for s in sent_count_test if (len(s) > 0 and s != "\n")]
sent_count_test[0:5]

[9, 30, 25, 33, 29]

In [15]:
aspect_rating_test = list(open(dataset_dir + rating_file[TEST_DATA], "r").readlines())
aspect_rating_test = [s for s in aspect_rating_test if (len(s) > 0 and s != "\n")]
aspect_rating_test[0:5]

['2 1 1 4 2 2 \n',
 '3 3 2 3 4 4 \n',
 '5 5 5 4 5 5 \n',
 '4 3 4 4 4 5 \n',
 '4 5 4 5 5 5 \n']

In [16]:
aspect_rating_test = [s.split(" ") for s in aspect_rating_test]
aspect_rating_test = np.array(aspect_rating_test)[:, 0:-1]
aspect_rating_test = aspect_rating_test.astype(np.int) - 1
aspect_rating_test[0:5]

array([[1, 0, 0, 3, 1, 1],
       [2, 2, 1, 2, 3, 3],
       [4, 4, 4, 3, 4, 4],
       [3, 2, 3, 3, 3, 4],
       [3, 4, 3, 4, 4, 4]])

In [17]:
sents_test = list(open(dataset_dir + content_file[TEST_DATA], "r").readlines())
sents_test = [s.strip() for s in sents_test]
len(sents_test)

88444

In [18]:
sents_test[0:5]

["definitely not a 5 star resort i 'm dumbfounded that this hotel gets good reviews and is so highly rated",
 "it 's decidedly a 3 star property , not 5 stars as indicated",
 'the rooms are very dated and run down , old crappy beds and pillows , an old tv and overall poorly maintained',
 'the whole property is pretty run down and old - looking',
 'the food is subpar , not one meal i had would be called great']

In [19]:
docs_test = concat_to_doc(sents_test, sent_count_test)
docs_test[0]

"definitely not a 5 star resort i 'm dumbfounded that this hotel gets good reviews and is so highly rated . it 's decidedly a 3 star property , not 5 stars as indicated . the rooms are very dated and run down , old crappy beds and pillows , an old tv and overall poorly maintained . the whole property is pretty run down and old - looking . the food is subpar , not one meal i had would be called great . the service is uneven and the staff is poorly trained and uninformed . many do not comprehend english . the beach is great , it 's the only redeeming factor . however the resort is a 1- hour taxi trip from the airport"

In [20]:
df_test = pd.DataFrame(docs_test)
df_test.head()

0
0  definitely not a 5 star resort i 'm dumbfounde...
1  facilities need work . we visited excellence f...
2  excellence was exactly that . my family and i ...
3  great service , nice hotel , mediocre food . m...
4  very relaxing experience just returned from my...

In [24]:
lmdb = TextLMDataBunch.from_df("./data/", train_df=df_train, valid_df=df_test, text_cols=0)

In [27]:
lmdb.show_batch()

In [30]:
x,y = next(iter(lmdb.train_dl))

In [31]:
x

tensor([[ 381,  115, 5829,  ..., 3138,   10,   58],
        [ 594,   12,   52,  ...,   45,  608,  845],
        [  12,   14, 1789,  ...,   19,   66,   24],
        ...,
        [  34,  607,   11,  ...,   87,   19,   57],
        [  28,   28,   16,  ...,   19,   14, 2707],
        [   2,  449,  107,  ...,   19,    9, 6772]], device='cuda:0')

In [32]:
y

tensor([[  115,  5829,    16,  ...,    10,    58,   789],
        [   12,    52,    21,  ...,   608,   845,    34],
        [   14,  1789,  1050,  ...,    66,    24,    82],
        ...,
        [  607,    11,    12,  ...,    19,    57,    18],
        [   28,    16, 10502,  ...,    14,  2707,  1339],
        [  449,   107,     9,  ...,     9,  6772,    15]], device='cuda:0')

In [33]:
type(x)

torch.Tensor

In [39]:
example = x[:15,:15].cpu()

In [40]:
example

tensor([[  381,   115,  5829,    16,    39,    65,   361,    49,    14,   106,
           186,  5829,   212,   297,   962],
        [  594,    12,    52,    21,    84,   121,    14,   268,    69,    17,
            53,    20,   204,   703,    36],
        [   12,    14,  1789,  1050,   341,   420,   239,    25,   408,    10,
             9,   865,   248,    13,  1421],
        [   10,    52,    23,    65,   535,    13,   166,    23,   368,   169,
            13,   141,   104,   681,    25],
        [   69,    87,    25,   408,   184,   185,   502,  1054,   914,    13,
             9,  2721,    15,     9,    57],
        [  494,    34,    35,     9,  1085,    69,    10,   882,   499,   123,
           290,    19,     9,   178,    24],
        [  526,    25,    86,    11,   244,    10,    73,    15,    99,    77,
            10,   273,    36,    33,     0],
        [  162,    21,    15,  1077,    80,  1667,   218,    10,     9,    51,
            15,   303,    10,    21,    15],
        

In [41]:
pd.DataFrame([lmdb.train_ds.vocab.textify(l).split(' ') for l in example])

0        1        2             3          4      5         6   \
0   fantastic    place     xmas            we       have   just  returned   
1           *      and       if            it         's   been         a   
2         and        a      ten        dollar        tip  later   arrived   
3           .       if      you          just      start     to       say   
4         day     stay       at    excellence      punta   cana   between   
5      change      our     room           the  following    day         .   
6       quiet       at    night             ,        etc      .     which   
7       where       it      was       missing       some  tiles    though   
8         off       to     your  accomodation          .     we      were   
9     staying       in      the         royal    service      .     bring   
10      newer  resorts     have     surpassed         it     in  amenites   
11  announcer     told       us         about         20      +     times   
12      which     they      are        listed        was    the    groups   
13      suite       to  request             a       room     on       the   
14         is      the      1st          time          i   have    stayed   

         7           8        9      10        11         12      13     14  
0      from           a        2   week      xmas        new    year  break  
1       hot         day        i  would       not  recommend  eating  there  
2        at  excellence        .    the     drive    nothing      to  worry  
3       you         're    going     to     check       more  prices     at  
4     march         3rd       to    the      10th        was     the    one  
5   despite     waiting      two  hours        in        the   lobby    for  
6       was      really     nice      .  everyone      there     had  xxunk  
7         .         the    beach    was   amazing          .      it    was  
8     round         the   corner      ,     block         12       ,   next  
9         a    stroller        .  cause       the       kids    will    not  
10      and      beauty        .    the     worst      thing   about    the  
11      not          to    brush    our     teeth       with     the    tap  
12     take          on  quality   from     great         to      ok      .  
13   second          or    third  floor       for      xxunk   ocean  views  
14       at          an       ai    and     there        was      nt   more

### start train

In [42]:
moms = (0.8,0.7)

In [ ]:
learn = language_model_learner(lmdb, AWD_LSTM)
learn.unfreeze()
learn.fit_one_cycle(4, slice(1e-2), moms=moms)