In [0]:
import torch

In [0]:
x = torch.empty(5, 3)
x

tensor([[1.1043e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])

In [0]:
x = torch.rand(5, 3)
x

tensor([[0.2313, 0.5401, 0.5050],
        [0.7517, 0.8895, 0.3500],
        [0.5937, 0.4996, 0.8806],
        [0.7503, 0.1288, 0.3824],
        [0.8435, 0.7879, 0.6961]])

In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x.size()

torch.Size([5, 3])

In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
x + y

tensor([[1.7172, 1.0036, 1.1105],
        [0.7931, 0.9288, 0.5751],
        [1.2285, 1.5367, 1.4068],
        [0.4634, 1.2130, 1.5342],
        [1.3863, 0.6419, 1.2102]])

In [0]:
y = torch.ones(5, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
y.add_(x)
y

tensor([[1.7503, 1.8327, 1.4162],
        [1.2800, 1.3350, 1.2920],
        [1.7647, 1.5629, 1.4412],
        [1.1677, 1.6407, 1.8286],
        [1.5611, 1.5597, 1.9913]])

In [0]:
y[0,0]

tensor(1.7503)

In [0]:
y[:,0]

tensor([1.7503, 1.2800, 1.7647, 1.1677, 1.5611])

In [0]:
y[:,-1]

tensor([1.4162, 1.2920, 1.4412, 1.8286, 1.9913])

In [0]:
z = y.view(15)
z

tensor([1.7503, 1.8327, 1.4162, 1.2800, 1.3350, 1.2920, 1.7647, 1.5629, 1.4412,
        1.1677, 1.6407, 1.8286, 1.5611, 1.5597, 1.9913])

In [0]:
y[0,0] = 0
z

tensor([0.0000, 1.8327, 1.4162, 1.2800, 1.3350, 1.2920, 1.7647, 1.5629, 1.4412,
        1.1677, 1.6407, 1.8286, 1.5611, 1.5597, 1.9913])

In [0]:
n = z.numpy()
n

array([0.       , 1.8327383, 1.4162428, 1.2799877, 1.3349773, 1.2920158,
       1.7647038, 1.5628704, 1.4411547, 1.1677325, 1.6406846, 1.82865  ,
       1.5611274, 1.5596764, 1.9913297], dtype=float32)

In [0]:
z.add_(1)

tensor([1.0000, 2.8327, 2.4162, 2.2800, 2.3350, 2.2920, 2.7647, 2.5629, 2.4412,
        2.1677, 2.6407, 2.8286, 2.5611, 2.5597, 2.9913])

# CUDA TEST

In [0]:
x = torch.rand(4,4)
x

tensor([[0.8344, 0.0769, 0.5680, 0.9492],
        [0.7749, 0.3409, 0.2765, 0.9372],
        [0.6996, 0.7475, 0.6960, 0.6100],
        [0.9155, 0.8123, 0.4514, 0.1668]])

In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.8344, 1.0769, 1.5680, 1.9492],
        [1.7749, 1.3409, 1.2765, 1.9372],
        [1.6996, 1.7475, 1.6960, 1.6100],
        [1.9155, 1.8123, 1.4514, 1.1668]], device='cuda:0')
tensor([[1.8344, 1.0769, 1.5680, 1.9492],
        [1.7749, 1.3409, 1.2765, 1.9372],
        [1.6996, 1.7475, 1.6960, 1.6100],
        [1.9155, 1.8123, 1.4514, 1.1668]], dtype=torch.float64)


In [0]:
device

device(type='cuda')

In [0]:
torch.cuda.is_available()

True

# AUTOGRAD

In [0]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [0]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [0]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [0]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [0]:
out.backward()

In [0]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

# Load DataBunch

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
%cd /content/gdrive/My Drive/Colab Notebooks/2019NN/

/content/gdrive/My Drive/Colab Notebooks/2019NN


In [7]:
!ls

data			     LMTrainer_Hotel_orig.ipynb  notes.py
data_helpers		     myloader.py		 text.ipynb
LMTrainer_Hotel_colab.ipynb  notes.ipynb		 torch_exp.ipynb


In [0]:
import fastai
from fastai.text import *

In [0]:
hotel_lm_databunch = load_data(path="./data/", file="hotel_lm_databunch")

In [8]:
hotel_lm_databunch.show_batch()

In [9]:
len(hotel_lm_databunch.vocab.itos)

23008

In [0]:
learn = language_model_learner(hotel_lm_databunch, AWD_LSTM, pretrained=False)

In [0]:
learn.path = Path("./data/")

In [12]:
learn.model

SequentialRNN(
  (0): AWD_LSTM(
    (encoder): Embedding(23008, 400, padding_idx=1)
    (encoder_dp): EmbeddingDropout(
      (emb): Embedding(23008, 400, padding_idx=1)
    )
    (rnns): ModuleList(
      (0): WeightDropout(
        (module): LSTM(400, 1152, batch_first=True)
      )
      (1): WeightDropout(
        (module): LSTM(1152, 1152, batch_first=True)
      )
      (2): WeightDropout(
        (module): LSTM(1152, 400, batch_first=True)
      )
    )
    (input_dp): RNNDropout()
    (hidden_dps): ModuleList(
      (0): RNNDropout()
      (1): RNNDropout()
      (2): RNNDropout()
    )
  )
  (1): LinearDecoder(
    (decoder): Linear(in_features=400, out_features=23008, bias=True)
    (output_dp): RNNDropout()
  )
)

In [0]:
learn = learn.load('lang_model')

# NEURAL NETWORKS

In [0]:
import torch.nn as nn
import torch.nn.functional as F

In [0]:
a = torch.randint(0, 100, (2,2,3) ).cuda()
a

tensor([[[51, 50, 95],
         [53, 39, 30]],

        [[75, 57, 82],
         [62, 39, 22]]], device='cuda:0')

In [0]:
besta = torch.randn(64, 10)
a[1,]

tensor([ 0.9337,  0.4397,  0.1969,  0.3553, -1.4252,  1.8536,  2.4727, -1.2416,
        -0.1950,  0.5891])

In [0]:
b = torch.randint(0, 500, (3,10)).cuda()
b

tensor([[447, 453, 158, 352, 258, 222, 340, 344, 497, 334],
        [ 77, 264, 363, 418, 175, 277, 440, 122, 451, 457],
        [208,  84, 131, 483, 322,  62, 164, 462, 376, 278]], device='cuda:0')

In [0]:
nn.Linear()

TypeError: ignored

In [0]:
encoder = learn.model[0]
encoder = encoder.eval()

In [0]:
raw_outputs, outputs = encoder(a)
result = outputs[2]
result

ValueError: ignored

In [0]:
result.shape

torch.Size([3, 10, 400])

In [0]:
sent_num_file = ["aspect_0.count", "test_aspect_0.count"]
rating_file = ["aspect_0.rating", "test_aspect_0.rating"]
content_file = ["aspect_0.txt", "test_aspect_0.txt"]
TRAIN_DATA = 0
dataset_dir = "./data/hotel_balance_LengthFix1_3000per/"

In [15]:
sent_count_train = list(open(dataset_dir + sent_num_file[TRAIN_DATA], "r").readlines())
sent_count_train = [int(s) for s in sent_count_train if (len(s) > 0 and s != "\n")]
sent_count_train[0:5]

[10, 14, 14, 24, 23]

In [16]:
sents_train = list(open(dataset_dir + content_file[TRAIN_DATA], "r").readlines())
sents_train = [s.strip() for s in sents_train]
len(sents_train)

265556

In [18]:
sents_train[0]

'we had the most wonderful time at the excellence'

In [19]:
sent_lens = [len(s)+1 for s in sents_train]
sent_lens[0:5]

[49, 72, 92, 55, 65]

In [0]:
class DocNN(nn.Module):
    def __init__(self, encoder):
        self.enc = encoder
        
    def forward(self, x):
        