In [0]:
import torch

In [0]:
x = torch.empty(5, 3)
x

tensor([[1.8689e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.0872e-05, 5.3488e+22, 6.5261e-10],
        [2.6951e-09, 8.1808e+20, 2.1747e+23],
        [2.6964e+23, 3.3240e+21, 5.0948e-14]])

In [0]:
x = torch.rand(5, 3)
x

tensor([[0.5961, 0.5121, 0.0091],
        [0.7040, 0.0940, 0.3053],
        [0.2704, 0.2869, 0.1678],
        [0.3840, 0.4807, 0.9710],
        [0.8896, 0.8984, 0.0815]])

In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x.size()

torch.Size([5, 3])

In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
x + y

tensor([[0.8063, 1.4389, 1.1374],
        [0.9737, 0.5097, 0.3425],
        [0.8730, 0.3819, 1.0785],
        [0.3462, 0.6835, 1.1477],
        [0.5032, 1.7907, 0.9460]])

In [0]:
y = torch.ones(5, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
y.add_(x)
y

tensor([[1.5158, 1.6061, 1.1491],
        [1.7461, 1.4313, 1.2521],
        [1.6116, 1.1298, 1.9098],
        [1.0280, 1.0426, 1.9316],
        [1.4596, 1.9537, 1.5580]])

In [0]:
y[0,0]

tensor(1.5158)

In [0]:
y[:,0]

tensor([1.5158, 1.7461, 1.6116, 1.0280, 1.4596])

In [0]:
y[:,-1]

tensor([1.1491, 1.2521, 1.9098, 1.9316, 1.5580])

In [0]:
z = y.view(15)
z

tensor([1.5158, 1.6061, 1.1491, 1.7461, 1.4313, 1.2521, 1.6116, 1.1298, 1.9098,
        1.0280, 1.0426, 1.9316, 1.4596, 1.9537, 1.5580])

In [0]:
y[0,0] = 0
z

tensor([0.0000, 1.6061, 1.1491, 1.7461, 1.4313, 1.2521, 1.6116, 1.1298, 1.9098,
        1.0280, 1.0426, 1.9316, 1.4596, 1.9537, 1.5580])

In [0]:
n = z.numpy()
n

array([1.       , 2.6061077, 2.1490824, 2.7461436, 2.4312887, 2.252097 ,
       2.6116178, 2.1297886, 2.9098234, 2.0280228, 2.0425963, 2.9315748,
       2.4596472, 2.9536724, 2.5579615], dtype=float32)

In [0]:
z.add_(1)

tensor([2.0000, 3.6061, 3.1491, 3.7461, 3.4313, 3.2521, 3.6116, 3.1298, 3.9098,
        3.0280, 3.0426, 3.9316, 3.4596, 3.9537, 3.5580])

# CUDA TEST

In [0]:
x = torch.rand(4,4)
x

tensor([[0.5113, 0.8185, 0.4570, 0.6576],
        [0.1926, 0.2661, 0.6034, 0.7706],
        [0.5639, 0.2572, 0.1779, 0.3716],
        [0.3526, 0.3933, 0.0275, 0.6091]])

In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.5113, 1.8185, 1.4570, 1.6576],
        [1.1926, 1.2661, 1.6034, 1.7706],
        [1.5639, 1.2572, 1.1779, 1.3716],
        [1.3526, 1.3933, 1.0275, 1.6091]], device='cuda:0')
tensor([[1.5113, 1.8185, 1.4570, 1.6576],
        [1.1926, 1.2661, 1.6034, 1.7706],
        [1.5639, 1.2572, 1.1779, 1.3716],
        [1.3526, 1.3933, 1.0275, 1.6091]], dtype=torch.float64)


In [0]:
device

device(type='cuda')

In [0]:
torch.cuda.is_available()

True

# AUTOGRAD

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [6]:
z = y * y * 3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [8]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [9]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [12]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [0]:
out.backward()

In [14]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])